services:
  smtp2webhook:
    image: waicool20/smtp2webhook
    build: .
    container_name: smtp2webhook
    restart: always
    ports:
      - "8025:8025"
    environment:
      WEBHOOK_URL: https://discord.com/api/webhooks/... # Set this to discord webhook url    (required)
      MSG_USERNAME: Smtp2Webhook                        # Override for webhook user          (optional)
      HOSTNAME: 0.0.0.0                                 # Override for hostname to listen to (optional)
      PORT: 8025                                        # Override for port to listen to     (optional)
    